apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-db
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  serviceName: pg-db
  selector:
    matchLabels:
      app: pg-db
  replicas: 1
  template:
    metadata:
      labels:
        app: pg-db
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: db
      containers:
        - name: db
          image: postgres:14.2
          volumeMounts:
            - name: db-disk
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: docket
  volumeClaimTemplates:
    - metadata:
        name: db-disk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata: 
  name: pg-db-lb
spec:
  selector:
    app: pg-db
  ports:
    - port: 5432
      targetPort: 5432