apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      securityContext:
        fsGroup: 1001
      nodeSelector:
        cloud.google.com/gke-nodepool: db
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: testpassword
            - name: DB_HOST
              value: pg-db-lb
            - name: DB_NAME
              value: docket
            - name: POOL_MODE
              value: transaction
            - name: DEFAULT_POOL_SIZE
              value: '15'
            - name: MIN_POOL_SIZE
              value: '7'
            - name: RESERVE_POOL_SIZE
              value: '7'
            - name: MAX_CLIENT_CONN
              value: '10000'
            - name: MAX_DB_CONNECTIONS
              value: '30'
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
---
# PostgreSQL pgbouncer Service
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-lb
spec:
  selector:
    app: pgbouncer
  ports:
    - port: 5432
      targetPort: 5432